MDSPLY_STRING MACRO STRING
    MOV AX, OFFSET STRING

    MOV AH, 09H
    INT 21H
ENDM

ORG 100H
MSG1 DB "MICROPROCESSOR AND $"
MSG2 DB "MICROCONTROLLER LAB $"

.CODE
    MAIN PROC
        MOV AX, @DATA
        MOV DS, AX

        MDSPLY_STRING MSG1
        MDSPLY_STRING MSG2

        MOV AH, 4CH
        INT 21H
        MAIN ENDP
END MAIN
