.MODEL SMALL
.STACK 100H
.DATA
ARRAY DB 1, 1, 2, 2, 1, 1, 2, 1
ODD_SUM DB 0
EVEN_SUM DB 0
STR_ODD DB "ODD Digits: $"
STR_EVEN DB "EVEN Digits: $"

.CODE
EVEN_ODD MACRO
    MOV SI, OFFSET ARRAY
    MOV CX, 8
    MOV AL, 0
    MOV ODD_SUM, AL
    MOV EVEN_SUM, AL
SUM_LOOP:
    MOV AL, [SI]
    AND AL, 1
    JZ ADD_TO_EVEN
    MOV BL, [SI]
    ADD ODD_SUM, BL
    JMP NEXT
ADD_TO_EVEN:
    MOV BL, [SI]
    ADD EVEN_SUM, BL
NEXT:
    INC SI
    LOOP SUM_LOOP
ENDM

MAIN PROC
    MOV AX, @DATA
    MOV DS, AX  
    EVEN_ODD

    MOV DX, OFFSET STR_ODD
    MOV AH, 9h
    INT 21H
    MOV AL, ODD_SUM
    ADD AL, 30H
    MOV DL, AL
    MOV AH, 2
    INT 21H
    CALL NEWLINE

    MOV DX, OFFSET STR_EVEN
    MOV AH, 9h
    INT 21H
    MOV AL, EVEN_SUM
    ADD AL, 30H
    MOV DL, AL
    MOV AH, 2
    INT 21H
    CALL NEWLINE

    MOV AH, 4CH
    INT 21H

MAIN ENDP

NEWLINE PROC
    MOV AH, 2
    MOV DL, 13
    INT 21H
    MOV DL, 10
    INT 21H
    RET
NEWLINE ENDP

END MAIN
